apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo hello1; sleep 3600
    image: busybox
    name: multi-pod
    resources: {}
  - args:
    - /bin/sh
    - -c
    - echo hello2 hello2!; sleep 3600
    image: busybox
    name: multi-pod2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
