apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-init
  name: pod-with-init
spec:
  containers:
  - image: nginx
    name: pod-with-init
    ports:
    - containerPort: 80
    resources: {}
  initContainers:
  - args:
    - /bin/sh
    - -c
    - echo "Test" > /work-dir/index.html
    image: busybox
    name: init-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
