apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-init
  name: pod-with-init
spec:
  volumes:
  - name: my-volume
    emptyDir: {}
  containers:
  - image: nginx
    name: pod-with-init
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
      - name: my-volume
        mountPath: /usr/share/nginx/html
  initContainers:
  - args:
    - /bin/sh
    - -c
    - echo "Test" > /work-dir/index.html
    image: busybox
    name: init-container
    resources: {}
    volumeMounts:
      - name: my-volume
        mountPath: /work-dir
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
