apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cm-pod
  name: cm-pod
spec:
  containers:
  - args:
    - sh
    - -c
    - env; sleep 60000;
    image: busybox
    name: cm-pod
    resources: {}
    envFrom:
      - configMapRef:
         name: cm1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
