apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysecret2
  name: mysecret2
spec:
  containers:
  - image: nginx
    name: mysecret2
    resources: {}
    volumeMounts:
    - name: sec-vol
      mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: sec-vol
      secret: 
        secretName: secret2 
status: {}
