apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: user
  name: user
spec:
  containers:
  - image: nginx
    name: user
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: myuser
status: {}
