apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: option-pod
  name: option-pod
spec:
  containers:
  - image: nginx
    name: option-pod
    resources: {}
    env:
      - name: option
        valueFrom:
          configMapKeyRef:
            key: var5
            name: options
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
