apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: options-pod
  name: options-pod
spec:
  containers:
  - image: nginx
    name: options-pod
    resources: {}
    envFrom:
      - configMapRef:
          name: anotherone
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
