apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-volume
spec:
  containers:
    - name: pod-cm-volume
      image: nginx
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: anotherone 
  restartPolicy: Never

