network:
  version: 2
  renderer: networkd

  ethernets:
    enp1s0:
      dhcp4: no
      addresses: [192.168.86.11/24]
      routes:
        - to: default
          via: 192.168.86.1
      nameservers:
        addresses: [1.1.1.1,1.0.0.1]

