apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: volume
  name: volume
spec:
  containers:
  - image: redis
    name: volume
    resources: {}
    volumeMounts:
      - name: myvolume
        mountPath: /test/path
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: myvolume
      emptyDir: {}
status: {}
