apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bbox
  name: bbo3x
spec:
  nodeName: blue
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: bbox
    resources: {}
    volumeMounts:
      - name: pw-vol
        mountPath: /etc/foo
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: pw-vol
      persistentVolumeClaim:
        claimName: mypvc
